### ISSUE TITLE
How can I cite your work?

### ISSUE THREAD

**Issue by yhson135** [Jonas-Verhellen/MolecularGraphPareto#1]
Hi,

I've been using your NSGA code for my research and found it very useful. I'd like to cite your work in my upcoming work. Could you provide specific citation guidelines for this, like journal or conference?

Thanks for your great work!

**Comment by Jonas-Verhellen** [comment]
Hi,

Thank you very much for the  comment. I appreciate it! Please cite the following paper: "Graph-based molecular Pareto optimisation, Chem. Sci., 2022, 13 , 25, 7526-7535, The Royal Society of Chemistry". I'll add it to the readme as well. 

Looking forward to see what you've used it for!

Jonas
